### ISSUE TITLE
image don't sync

### ISSUE THREAD

**Issue by CatCodeMe** [saberzero1/quartz-syncer#5]
it seems that current version , image won't be pushed.

And is there any plan to support image 、canvas、excalidraw...

**Comment by CatCodeMe** [comment]
I check the code  `uploadAssets` , it works .  However, the path seems invalid. 

1. push success
![image](https://github.com/saberzero1/quartz-syncer/assets/11496772/23103e67-1dd3-4480-bf6e-cd4459815f76)


2. render failed , 404 

![image](https://github.com/saberzero1/quartz-syncer/assets/11496772/c98e97c3-472d-490c-9d79-f3faf5cce023)


3. use in obsidian  `![[20240217-t3.png]]`

**Comment by CatCodeMe** [comment]
I know how to fix ,   use `content` replace `src/site` in main.js's method `uploadImage()`,  it will works. It seems make 'content'  dir to an option will be better.

**Comment by CatCodeMe** [comment]
Another issue,  now I publish notes in obsidian with this plugin ,  modify  quartz config (may be change css) in my repository. 
There is a confict .
1.  push notes use plugin  in obsidian 
2. change css and push in repository,  use  `npx quartz sync` 
3. css change success,  **but notes pushed in step1 will be delete** !
4. I use a system link to  link obsidian dir, `1100_blog_content` to quartz `content` dir
5. other notes use `publish: true` 

in obsidian 
<img width="468" alt="image" src="https://github.com/saberzero1/quartz-syncer/assets/11496772/1ff0374a-e2dd-4a3b-9090-6d57f8f49408">

in quartz

![image](https://github.com/saberzero1/quartz-syncer/assets/11496772/4b7ba0c9-fd39-4ebe-b740-f92193114a03)

**Comment by saberzero1** [comment]
Hey, thanks for the detailed report.

I personally do not use `npx quartz sync`. I will look into the functionality of the command and see if I can integrate the dataview parsing into the default quartz functionality.

I will let you know when I have more details.

**Comment by saberzero1** [comment]
@CatCodeMe can you check if re-uploading the markdown files through this plugin after running `npx quartz sync`, does that resolve the missing pages?

I will keep you updated on the missing images.

**Comment by CatCodeMe** [comment]
> @CatCodeMe can you check if re-uploading the markdown files through this plugin after running `npx quartz sync`, does that resolve the missing pages?
> 
> I will keep you updated on the missing images.

yes, this plugin will re-uploading notes file with `publish: true` . However, it can be a bit inconvenient, as sometimes it's necessary to synchronize with the latest updates from the Quartz repository.

**Comment by CatCodeMe** [comment]
I know which cause this problem,  `npx quartz sync` has a method `handleSync()` in `handler.js` , has two method 

1. `stashContentFolder()` (before `git pull` to `mv content` to `.quartz-cache`) 
2. and `popContentFolder()`  (before `git push -uf` to `cp .quartz-cache/*  content` )

final I do like this to fix this problem 
10. remove these method (`stashContentFolder()`,  `popContentFolder()` ) , don't handle local content in local repo, use remote (obsidian publish) to override local content
11. `npx quartz create` , select `empty dir` ,  **don't use `systemLink` option**
12. create a `index.md` in content as homepage 
13. use this plugin in obsidian as usual. 

result is :
22. write and publish in obsidian 
23. update config (css, or other) in local repo
24. and no confict with `npx quartz sync` , whether `content` or `config`

little tip:
in `step 12`:   I have to  manually create `index.md` in local repo,  can't sync with obsidian (can't use sysLink).  

- maybe we could suppose a option , like  'homepage: true' , and number only be 1,  and always push to remote repo `content/`, 
- file name must be `index.md`
- finally , we can edit and publish all content files in obsidian ,  and local repo only for updating other config .

do you think so ?
